 * Serving Flask app 'search'
 * Debug mode: off
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8000
 * Running on http://172.30.198.152:8000
[33mPress CTRL+C to quit[0m
[2023-04-16 23:54:55,027] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/wsl/eecs485/p5-search-engine/env/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/wsl/eecs485/p5-search-engine/env/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/wsl/eecs485/p5-search-engine/env/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/wsl/eecs485/p5-search-engine/env/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/wsl/eecs485/p5-search-engine/search_server/search/views/main.py", line 79, in get_results
    return flask.render_template("search.html", **context)
  File "/home/wsl/eecs485/p5-search-engine/env/lib/python3.10/site-packages/flask/templating.py", line 146, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/home/wsl/eecs485/p5-search-engine/env/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/wsl/eecs485/p5-search-engine/env/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/wsl/eecs485/p5-search-engine/env/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/wsl/eecs485/p5-search-engine/env/lib/python3.10/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/home/wsl/eecs485/p5-search-engine/env/lib/python3.10/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/wsl/eecs485/p5-search-engine/env/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/wsl/eecs485/p5-search-engine/search_server/search/templates/search.html", line 33, in template
    {% endfor %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endfor'. You probably made a nesting mistake. Jinja is expecting this tag, but currently looking for 'endif'. The innermost block that needs to be closed is 'if'.
127.0.0.1 - - [16/Apr/2023 23:54:55] "[35m[1mGET /?q=pies&w=0.5 HTTP/1.1[0m" 500 -
